kind: Template
apiVersion: template.openshift.io/v1
metadata:
  name: gdx-agreements-tracker-app-deployment
  resourceVersion: "v1.0.0"
  annotations:
    openshift.io/display-name: Deployment GDX agreements tracker app.
    description: Deployment for GDX agreements tracker app.
    tags: pmo,app,gdx,agreements-tracker
parameters:
  - name: APP_NAME
    displayName: "App Name"
    description: "The name of the application (grouped)."
    required: true
    value: "gdx-agreements-tracker"
  - name: ROLE_NAME
    displayName: "Component Name"
    description: "The name of the application role."
    required: true
    value: "app"
  - name: PROJECT_NAMESPACE
    displayName: "OpenShift Project Namespace"
    description: "The namespace of the OpenShift project containing the application."
    required: true
    value: "acd38d"
  - name: ENV_NAME
    displayName: "Environment name"
    description: "The name for this environment [dev, test, prod, tools]"
    required: true
    value: "dev"
  - name: IMAGE_DEPLOY
    displayName: "Image deploy name"
    description: "This is the name of the deploy image."
    required: true
    value: "deploy"
  - name: INSTANCE
    displayName: "Unique Identifier"
    description: "A unique identifier to allow for multiple instances (i.e. '-01')."
    value: ""
  - name: APP_PORT
    displayName: "Application Port"
    description: "The port used to communicate with the Pod"
    value: "8080"

  - name: KEYCLOAK_CLIENT_ID
    displayName: "Keycloak Client ID"
    description: "The keycloak client id or resource"
    value: ""
    required: true
  - name: KEYCLOAK_URL
    displayName: "Keycloak URL"
    description: "The keycloak auth url"
    value: ""
    required: true
  - name: KEYCLOAK_REALM
    displayName: "Keycloak realm"
    description: "The keycloak realm"
    value: "standard"
  - name: APP_API_URL
    displayName: "API URL"
    description: "The react app api url"
    value: "/api"

  - name: REPLICAS
    displayName: "Pod Replicas"
    description: "Number of pod replicas to run"
    value: "1"
  - name: CPU_REQUEST
    displayName: "CPU Request"
    description: "Starting amount of CPU the container can use."
    value: "100m"
  - name: CPU_LIMIT
    displayName: "CPU Limit"
    description: "Maximum amount of CPU the container can use."
    value: "1"
  - name: MEMORY_REQUEST
    displayName: "Memory Request"
    description: "Starting amount of memory the container can use."
    value: "100Mi"
  - name: MEMORY_LIMIT
    displayName: "Memory Limit"
    description: "Maximum amount of memory the container can use."
    value: "2Gi"
objects:
  - kind: Deployment
    apiVersion: apps/v1
    metadata:
      name: ${APP_NAME}-${ROLE_NAME}${INSTANCE}
      namespace: ${PROJECT_NAMESPACE}-${ENV_NAME}
      annotations:
        image.openshift.io/triggers: >-
          [{"from":{"kind":"ImageStreamTag","name":"gdx-agreements-tracker-app-run:dev","namespace": "${PROJECT_NAMESPACE}-tools"},"fieldPath":"spec.template.spec.containers[?(@.name==\"${APP_NAME}-${ROLE_NAME}\")].image"}]
      labels:
        app.kubernetes.io/part-of: ${APP_NAME}
        app.openshift.io/runtime: nodejs
        app.kubernetes.io/component: frontend
    spec:
      replicas: ${{REPLICAS}}
      selector:
        matchLabels:
          name: ${APP_NAME}-${ROLE_NAME}${INSTANCE}
          app: ${APP_NAME}
          role: ${ROLE_NAME}
          env: ${ENV_NAME}
      template:
        metadata:
          labels:
            name: ${APP_NAME}-${ROLE_NAME}${INSTANCE}
            app: ${APP_NAME}
            role: ${ROLE_NAME}
            env: ${ENV_NAME}
        spec:
          containers:
            - name: ${APP_NAME}-${ROLE_NAME}
              image: image-registry.openshift-image-registry.svc:5000/${PROJECT_NAMESPACE}-tools/${APP_NAME}-${ROLE_NAME}-run:dev
              imagePullPolicy: Always
              env:
                REACT_APP_API_URL: ${APP_API_URL}
                REACT_APP_KEYCLOAK_URL: ${KEYCLOAK_URL}
                REACT_APP_KEYCLOAK_CLIENT_ID: ${KEYCLOAK_CLIENT_ID}
                REACT_APP_KEYCLOAK_REALM: ${KEYCLOAK_REALM}
              ports:
                - containerPort: ${{APP_PORT}}
                  protocol: TCP
              resources:
                requests:
                  cpu: ${CPU_REQUEST}
                  memory: ${MEMORY_REQUEST}
                limits:
                  cpu: ${CPU_LIMIT}
                  memory: ${MEMORY_LIMIT}
