# dependabot for checking docker images for updates
---
version: 2
updates:
  # Maintain dependencies for postgres image
  - package-ecosystem: "docker"
    directory: "openshift/templates/images/postgres"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 0
    reviewers:
      - bcgov/digital-engagement-solutions-custom-web

  # Maintain dependencies for NGINX web server image
  - package-ecosystem: "docker"
    directory: "openshift/templates/images/nginx/docker"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 0
    reviewers:
      - bcgov/digital-engagement-solutions-custom-web

  # Maintain dependencies for NodeJS image
  - package-ecosystem: "docker"
    directory: "openshift/templates/images/nodejs"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 0
    reviewers:
      - bcgov/digital-engagement-solutions-custom-web
---
# dependabot for checking FRONTEND npm packages for updates (and creating PRS)
version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/frontend"
    schedule:
      interval: "daily" # this should be changed to "weekly" after we confirm it works.
    create-pull-requests: false
    open-pull-requests-limit: 5
    # do not specify the target branch for security updates:
    #target-branches:
    #  - "development"
---
# dependabot for checking npm BACKEND packages for updates (and creating PRS)
version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/backend"
    schedule:
      interval: "daily" # this should be changed to "weekly" after we confirm it works.
    create-pull-requests: false
    # set a reasonable limit to pr requests
    open-pull-requests-limit: 5
    # do not specify the target branch for security updates:
    #target-branches:
    #  - "development"
