# dependabot for checking docker images for updates
---
version: 2
updates:
  # Maintain dependencies for nodeJS image
  - package-ecosystem: "docker"
    directory: "openshift/templates/images/nodejs"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 1
    reviewers:
      - bcgov/gdx-engagement-admin

  # Maintain dependencies for App image
  - package-ecosystem: "docker"
    directory: "openshift/templates/images/nodejs"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 1
    reviewers:
      - bcgov/gdx-engagement-admin
  # Maintain dependencies for API image
  - package-ecosystem: "docker"
    directory: "openshift/templates/images/nodejs"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 1
    reviewers:
      - bcgov/gdx-engagement-admin
  # Maintain dependencies for nginx webserver image
  - package-ecosystem: "docker"
    directory: "openshift/templates/images/nodejs"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 1
    reviewers:
      - bcgov/gdx-engagement-admin
  # Maintain dependencies for postgres database image



  ...
