version: '3'
# Use docker compose up --build

services:
    front-end:
        build:
            context: ./
            dockerfile: ./Dockerfile
        restart: always
        depends_on:
            - api
        ports:
            - 8080:80
