kind: "PersistentVolumeClaim"
apiVersion: v1
metadata:
  name: postgres-pvc
spec:
  accessModes:
    - "ReadWriteOnce"
  resources:
    requests:
      storage: "500Mi"
  storageClassName: netapp-block-standard
  volumeMode: Filesystem

---

kind: "PersistentVolumeClaim"
apiVersion: v1
metadata:
  name: postgres-pvc-audit-log
spec:
  accessModes:
    - "ReadWriteOnce"
  resources:
    requests:
      storage: "500Mi"
  storageClassName: netapp-file-standard
  volumeMode: Filesystem