version: "3"
x-env:
  POSTGRES_PASSWORD: &POSTGRES_PASSWORD postgres
  POSTGRES_USER: &POSTGRES_USER postgres
  POSTGRES_HOST: &POSTGRES_HOST db
  POSTGRES_PORT: &POSTGRES_PORT 5432
  POSTGRES_DATABASE: &POSTGRES_DATABASE gat_db
  DATABASE_AUTO_DEPLOY: &DATABASE_AUTO_DEPLOY 1
volumes:
  database:
  database_log:
services:
  db:
    build: 
      dockerfile: Dockerfile
      context: ../openshift/templates/images/postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: *POSTGRES_PASSWORD
      POSTGRES_USER: *POSTGRES_USER
    volumes:
      - database:/var/lib/postgresql/data
      - ../openshift/templates/images/postgres/postgresql.conf:/home/postgresql.conf
      #- ../logs/postgresql:/var/log/postgresql
    networks:
      - gat-db
    ports:
      - "15432:5432"
networks:
  gat-db:
    driver: bridge