apiVersion: v1
kind: PersistentVolumeClaim
namespace: acd38d-dev
metadata:
  labels:
    app: backup-container
    env: v1
    name: pmo-backup
    role: backup-container
  name: pmo-backup-pvc
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: netapp-file-backup
---
apiVersion: v1
kind: PersistentVolumeClaim
namespace: acd38d-dev
metadata:
  labels:
    app: backup-container
    env: v1
    name: pmo-backup
    role: backup-container
  name: pmo-backup-verification-pvc
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: netapp-file-standard