apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default
namePrefix: pmo-
commonLabels:
  app: gdx-agreements-tracker
  env: local
resources:
  - backup-db-cron.yaml
  - backup-db-volumes.yaml
# Configuration for backup
configMapGenerator:
  - name: pmo-backup-config-volume
    behavior: merge
    literals:
    - backup.conf=postgres=deployment:5432/postgres
    - POSTGRES_DB=secret_postgres_db
    - POSTGRES_USER=secret_postgres_user
    - POSTGRES_REGULAR_USER=secret_postgres_regular_user
    - POSTGRES_HOST=secret_postgres_host
secretGenerator:
- name: secrets
  type: Opaque
  literals:
  - POSTGRES_PASSWORD=secrets_postgres_password_generated
  - POSTGRES_REGULAR_USER_PASSWORD=secret_postgres_regular_user_password_generated
