apiVersion: batch/v1
kind: CronJob
namespace: acd38d-dev
metadata:
  name: pmo-backup-cron
  annotations:
    openshift.io/display-name:  Cron job templates for backups.
    description: CronJob to backup gdx-agreements-tracker database, https://developer.gov.bc.ca/Backup-Container.
    tags: backups,pmo,postgres,gdx-agreements-tracker
  labels:
    template: "pmo-postgres-cron-cronjob"
    cronjob: "pmo-postgres-cron-backup"
spec:
# TODO - finish updating this based on backup-db-cron.yaml from wordpres repo: deployments/kustomize/base/backups
  replicas: 1
  selector:
    name: pmo-backup
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: backup-container
        env: v1
        name: pmo-backup
        role: backup-container
      name: pmo-backup
    spec:
      containers:
      - env:
        - name: BACKUP_STRATEGY
          value: rolling
        - name: BACKUP_DIR
          value: /backups/
        - name: NUM_BACKUPS
          value: ""
        - name: DAILY_BACKUPS
          value: ""
        - name: WEEKLY_BACKUPS
          value: ""
        - name: MONTHLY_BACKUPS
          value: "3"
        - name: BACKUP_PERIOD
          value: ""
        - name: DATABASE_SERVICE_NAME
          value: ""
        - name: DATABASE_NAME
          value: ""
        - name: TABLE_SCHEMA
          value: public
        - name: POSTGRES_USER
          value: postgres
        - name: POSTGRES_PASSWORD
          value: "nW2Kxj)c>19[X$]_Q+evU88fM8"
        - name: ENVIRONMENT_FRIENDLY_NAME
          value: GDX Agreements Tracker Postgresql Backups
        - name: ENVIRONMENT_NAME
          value: dev
        image: "bcgovimages/backup-container:latest"
        name: pmo-backup
        ports: []
        resources:
          limits:
            cpu: "0"
            memory: 0Mi
          requests:
            cpu: "0"
            memory: 0Mi
        volumeMounts:
        - mountPath: /backups/
          name: pmo-backup-pvc
        - mountPath: /var/lib/pgsql/data
          name: pmo-backup-verification-pvc
        - mountPath: /backup.conf
          name: pmo-backup-config-volume
          subPath: backup.conf
      volumes:
      - name: pmo-backup-pvc
        persistentVolumeClaim:
          claimName: pmo-backup-pvc
      - name: pmo-backup-verification-pvc
        persistentVolumeClaim:
          claimName: pmo-backup-verification-pvc
      - configMap:
          items:
          - key: backup.conf
            path: backup.conf
          name: backup-conf
        name: pmo-backup-config-volume
  triggers:
  - type: ConfigChange
  - imageChangeParams:
      automatic: true
      containerNames:
      - pmo-backup
      from:
        kind: ImageStreamTag
        name: pmo-backup:v1
        namespace: acd38d-tools
    type: ImageChange
