kind: CronJob
apiVersion: batch/v1
metadata:
  name: pmo-postgres-backup-cron
  annotations:
    openshift.io/display-name:  Cron job templates for backups.
    description: Cron job to backup PMO database, https://developer.gov.bc.ca/Backup-Container.
    tags: backups,PMO,postgres
  labels:
    template: "pmo-postgres-cron-cronjob"
    cronjob: "pmo-postgres-cron-backup"
spec:
  schedule: "30 10 * * *" # 10:30am UTC = 2:30am PST
  concurrencyPolicy: "Forbid"
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 2
  jobTemplate:
    metadata:
      labels:
        template: "pmo-postgres-cron-job"
        cronjob: "pmo-postgres-cron-backup"
    spec:
      backoffLimit: 0
      template:
        metadata:
          labels:
            template: "pmo-postgres-cron-job"
            cronjob: "pmo-postgres-cron-backup"
        spec:
          containers:
            - name: pmo-postgres-backup-runner
              image: backup-container-postgres
              command:
                - "/bin/bash"
                - "-c"
                - "/backup.sh -1"
              volumeMounts:
              - name: pmo-postgres-backup-db
                mountPath: /backups/
              - name: pmo-postgres-backup-verification
                mountPath: /var/lib/postgresql/
              - name: pmo-postgres-backup-config
                # but where is backup.conf, really?
                mountPath: /backup.conf
                subPath: backup.conf
              env:
              - name: BACKUP_STRATEGY
                value: rolling
              - name: BACKUP_DIR
                valueFrom:
                  configMapKeyRef:
                    name: pmo-postgres-backup-config
                    key: BACKUP_DIR
              - name: MONTHLY_BACKUPS
                value: "3"
              - name: DATABASE_USER
                valueFrom:
                  configMapKeyRef:
                    name: pmo-postgres-backup-config
                    key: POSTGRES_USER
              - name: DATABASE_PASSWORD
                valueFrom:
                  secretKeyRef:
                    name: pmo-postgres-backup-secrets
                    key: MYSQL_PASSWORD
          volumes:
            - name: pmo-postgres-backup-db
              persistentVolumeClaim:
                claimName: pmo-postgres-backup-db
            - name: pmo-postgres-backup-verification
              persistentVolumeClaim:
                claimName: pmo-postgres-backup-verification
            - name: pmo-postgres-backup-config
              configMap:
                name: pmo-postgres-backup-config
                items:
                  - key: backup.conf
                    path: backup.conf
          restartPolicy: "Never"
          terminationGracePeriodSeconds: 30
          activeDeadlineSeconds: 1600
          dnsPolicy: "ClusterFirst"
          serviceAccountName: "default"
          serviceAccount: "default"