# ImageStream api-run
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  annotations:
    description: Image for the gdx agreements application backend built from nodejs s2i
  labels:
    role: api
  name: api-run

---
# BuildConfig api-run
apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  annotations:
    description: The backend api image build config using s2i nodejs build with api/run with migration, seeds and cmd node server.js 
  labels:
    role: api
  name: api-run
spec:
  failedBuildsHistoryLimit: 1
  successfulBuildsHistoryLimit: 2
  strategy:
    sourceStrategy:
      from:
        kind: ImageStreamTag
        name: gdx-agreements-tracker-node-s2i:latest
      incremental: false
    type: source
  source:
    contextDir: backend
    git:
      ref: development
      uri: https://github.com/bcgov/gdx-agreements-tracker.git
    type: Git
  output:
    to:
      kind: ImageStreamTag
      name: gdx-agreements-tracker-api-run:dev
  resources:
    limits:
      cpu: "1"
      memory: 1Gi
    requests:
      cpu: "500m"
      memory: 500Mi
  runPolicy: Serial