# ImageStream app-run
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  annotations:
    description: This is the image stream for the app run
  labels:
    role: app
  name: app-run

---
# BuildConfig app-run
apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  annotations:
    description: Compiles the React application and uses Nginx (multi-stage build)for GDX agreements tracker.
  labels:
    role: app
  name: app-run
spec:
  failedBuildsHistoryLimit: 1
  successfulBuildsHistoryLimit: 1
  strategy:
    type: Docker
  source:
    contextDir: frontend
    git:
      ref: feature/descw-1735-buildconfig-cleanup
      uri: https://github.com/bcgov/gdx-agreements-tracker.git
    type: Git
    images:
      - from:
          kind: ImageStreamTag
          name: gdx-agreements-tracker-node-s2i:latest
        as: 
          - node-s2i
      - from:
          kind: ImageStreamTag
          name: gdx-agreements-tracker-nginx-s2i:latest    
        as: 
          - nginx-s2i
  output:
    to:
      kind: ImageStreamTag
      name: gdx-agreements-tracker-app-run:dev
  resources:
    limits:
      cpu: "1"
      memory: 2Gi
    requests:
      cpu: "0.8m"
      memory: 1Gi
  runPolicy: Serial

---
# BuildConfig app-build
apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  annotations:
    description: Compiles the React application for GDX agreements tracker.
  labels:
    role: app
  name: app-run
spec:
  failedBuildsHistoryLimit: 1
  successfulBuildsHistoryLimit: 1
  strategy:
    dockerStrategy:
      from:
        kind: ImageStreamTag
        name: gdx-agreements-tracker-nginx-s2i:latest
    type: Docker
  source:
    dockerfile: |-
      FROM scratch
      COPY * /tmp/app/dist/
      USER root
      RUN ln -sf /etc/nginx/publicServerEnvironmentSettings.js  /tmp/app/dist/publicServerEnvironmentSettings.js
      USER 104
      RUN ls -la /tmp/app/dist
      CMD  /usr/libexec/s2i/run
    images:
    - from:
        kind: ImageStreamTag
        name: gdx-agreements-tracker-app-build:dev
      paths:
      - destinationDir: tmp
        sourcePath: /tmp/build/.
    type: Dockerfile
  output:
    to:
      kind: ImageStreamTag
      name: gdx-agreements-tracker-app-run:dev
  resources:
    limits:
      cpu: "1"
      memory: 1Gi
    requests:
      cpu: "500m"
      memory: 0.5Gi
  runPolicy: Serial