# ImageStream app-run
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  annotations:
    description: This is the image stream for the app run
  labels:
    role: app
  name: app-run

---
# BuildConfig app-run
apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  annotations:
    description: Compiles the React application and uses Nginx (multi-stage build)for GDX agreements tracker.
  labels:
    role: app
  name: app-run
spec:
  failedBuildsHistoryLimit: 1
  successfulBuildsHistoryLimit: 1
  strategy:
    type: Docker
  source:
    contextDir: frontend
    git:
      ref: development
      uri: https://github.com/bcgov/gdx-agreements-tracker.git
    type: Git
    images:
      - from:
          kind: ImageStreamTag
          name: gdx-agreements-tracker-node-s2i:latest
        as: 
          - node-s2i
      - from:
          kind: ImageStreamTag
          name: gdx-agreements-tracker-nginx-s2i:latest    
        as: 
          - nginx-s2i
  output:
    to:
      kind: ImageStreamTag
      name: gdx-agreements-tracker-app-run:dev
  resources:
    limits:
      cpu: "3"
      memory: 4Gi
    requests:
      cpu: "2"
      memory: 3Gi
  runPolicy: Serial