apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namePrefix: gdx-agreements-tracker-
commonLabels:
  env: tools
  app: gdx-agreements-tracker
resources:
- nodejs-s2i.yaml
- app.yaml
- api.yaml
- nginx.yaml
- postgres.yaml
