# ImageStream nginx-run
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  annotations:
    description: Nginx image for serving the frontend application.
  labels:
    role: nginx
  name: nginx-s2i
---
# BuildConfig nginx-run
apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  annotations:
    description: Creates the Nginx runtime container.
  labels:
    role: nginx
  name: nginx-s2i
spec:
  failedBuildsHistoryLimit: 1
  successfulBuildsHistoryLimit: 1
  strategy:
    dockerStrategy:
      from:
        kind: DockerImage
        name: nginx:1.25.3
    type: Docker
  source:
    contextDir: openshift/templates/images/nginx/docker
    git:
      ref: development
      uri: https://github.com/bcgov/gdx-agreements-tracker.git
    type: Git
  output:
    to:
      kind: ImageStreamTag
      name: gdx-agreements-tracker-nginx-s2i:latest
  runPolicy: Serial