# ImageStream for postgres-run
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  annotations:
    description: PostgreSQL database image.
  labels:
    role: postgresql
  name: postgres-run
spec:
  lookupPolicy:
    local: true
---
# BuildConfig for postgres-run
apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  annotations:
    description: PostgreSQL runtime container
  labels:
    role: postgres
  name: postgres-run
spec:
  completionDeadlineSeconds: 1800
  failedBuildsHistoryLimit: 1
  successfulBuildsHistoryLimit: 1
  strategy:
    dockerStrategy:
      dockerfilePath: Dockerfile
    type: Docker
  source:
    contextDir: /openshift/templates/images/postgres
    git:
      ref: development
      uri: https://github.com/bcgov/gdx-agreements-tracker.git
    type: Git
  output:
    to:
      kind: ImageStreamTag
      name: gdx-agreements-tracker-postgres-run:dev
  resources:
    limits:
      cpu: "200m"
      memory: 300Mi
  runPolicy: Serial
  
  
  