kind: Template
apiVersion: v1
metadata:
  name: postgres-14-image-stream
  annotations:
    openshift.io/display-name: PostgreSQL 14 Images
    description: ImageStream definitions for PostgreSQL 14 on alpine and bullseye that originate from Dockerhub
parameters:

  - name: APP_NAME
    displayName: "App Name"
    description: "The name of the application (grouped)."
    required: true
    value: "gdx-agreements-tracker"
  - name: ROLE_NAME
    displayName: "Component Name"
    description: "The name of the application role."
    required: true
    value: "postgres"
  - name: PROJECT_NAMESPACE
    displayName: "OpenShift Project Namespace"
    description: "The namespace of the OpenShift project containing the application."
    required: true
    value: "acd38d"
  - name: ENV_NAME
    displayName: "Environment name"
    description: "The name for this environment [dev, test, prod, tools]"
    required: true
    value: "tools"

objects:
  - kind: ImageStream
    apiVersion: v1
    metadata:
      name: postgres
      namespace: ${PROJECT_NAMESPACE}-${ENV_NAME}
      annotations:
        description: Keeps track of PostgreSQL 14 images that originate from Dockerhub
      labels:
        name: dockerhub-node-images
        app: ${APP_NAME}
        role: ${ROLE_NAME}
        env: ${ENV_NAME}
        source: dockerhub
    spec:
      tags:
        - name: "14.4-bullseye"
          from:
            kind: DockerImage
            name: "docker-remote.artifacts.developer.gov.bc.ca/postgres:14.4-bullseye"
          referencePolicy:
            type: Local
