apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  annotations:
    description: The build that generates artifacts (html, javascript, images, etc)
  labels:
    app: gdx-agreements-tracker
    env: tools
    role: api
  name: gdx-agreements-tracker-api-build
  namespace: acd38d-tools
spec:
  completionDeadlineSeconds: 1800
  failedBuildsHistoryLimit: 2
  output:
    to:
      kind: ImageStreamTag
      name: gdx-agreements-tracker-api-build:dev
  resources:
    limits:
      cpu: 1
      memory: 2Gi
  source:
    contextDir: backend
    dockerfile: ""
    git:
      ref: feature/descw-1128-upgrade-images-node-versions
      uri: https://github.com/bcgov/gdx-agreements-tracker.git
    type: Git
  strategy:
    sourceStrategy:
      from:
        kind: ImageStreamTag
        name: gdx-agreements-tracker-node-s2i:dev
      incremental: false
    type: Source
  successfulBuildsHistoryLimit: 2
  triggers:
  - type: ConfigChange
  - imageChange:
      from:
        kind: ImageStreamTag
        name: gdx-agreements-tracker-node-s2i:dev
    type: ImageChange
---
apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  annotations:
    description: Compiles the React application for GDX agreements tracker.
  labels:
    app: gdx-agreements-tracker
    env: tools
    role: api
  name: gdx-agreements-tracker-api-run
  namespace: acd38d-tools
spec:
  failedBuildsHistoryLimit: 2
  output:
    to:
      kind: ImageStreamTag
      name: gdx-agreements-tracker-api-run:dev
  resources:
    limits:
      cpu: "1"
      memory: 4Gi
    requests:
      cpu: "1"
      memory: 2Gi
  runPolicy: Serial
  source:
    dockerfile: |-
      FROM scratch
      COPY tmp /opt/app-root
      USER root
      RUN chmod -R 777 /opt/app-root/src/database/production_seeds /opt/app-root/.npm
      USER 1001
      CMD /usr/local/s2i/run
    images:
    - from:
        kind: ImageStreamTag
        name: gdx-agreements-tracker-api-build:dev
      paths:
      - destinationDir: tmp
        sourcePath: /opt/app-root/.
    type: Dockerfile
  strategy:
    dockerStrategy:
      from:
        kind: ImageStreamTag
        name: gdx-agreements-tracker-node-s2i:dev
      incremental: false
    type: Docker
  successfulBuildsHistoryLimit: 2
  triggers:
  - type: ConfigChange
  - imageChange:
      from:
        kind: ImageStreamTag
        name: gdx-agreements-tracker-node-s2i:dev
    type: ImageChange
  - imageChange:
      from:
        kind: ImageStreamTag
        name: gdx-agreements-tracker-api-build:dev
    type: ImageChange
---
apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  annotations:
    description: Compiles the React application for GDX agreements tracker.
  labels:
    app: gdx-agreements-tracker
    env: tools
    role: app
  name: gdx-agreements-tracker-app-build
  namespace: acd38d-tools
spec:
  failedBuildsHistoryLimit: 2
  output:
    to:
      kind: ImageStreamTag
      name: gdx-agreements-tracker-app-build:dev
  resources:
    limits:
      cpu: "2"
      memory: 8Gi
    requests:
      cpu: "2"
      memory: 7Gi
  runPolicy: Serial
  source:
    contextDir: frontend
    dockerfile: ""
    git:
      ref: feature/descw-1128-upgrade-images-node-versions
      uri: https://github.com/bcgov/gdx-agreements-tracker.git
    type: Git
  strategy:
    type: Docker
  successfulBuildsHistoryLimit: 2
  triggers:
  - type: ConfigChange
---
apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  annotations:
    description: Compiles the React application for GDX agreements tracker.
  labels:
    app: gdx-agreements-tracker
    env: tools
    role: app
  name: gdx-agreements-tracker-app-run
  namespace: acd38d-tools
spec:
  failedBuildsHistoryLimit: 2
  output:
    to:
      kind: ImageStreamTag
      name: gdx-agreements-tracker-app-run:dev
  resources:
    limits:
      cpu: "1"
      memory: 4Gi
    requests:
      cpu: "1"
      memory: 2Gi
  runPolicy: Serial
  source:
    dockerfile: |-
      FROM gdx-agreements-tracker-nginx-run:dev
      COPY * /tmp/app/dist/
      USER root
      RUN ln -sf /etc/nginx/publicServerEnvironmentSettings.js  /tmp/app/dist/publicServerEnvironmentSettings.js
      USER 104
      CMD  /usr/libexec/s2i/run
    images:
    - from:
        kind: ImageStreamTag
        name: gdx-agreements-tracker-app-build:dev
      paths:
      - destinationDir: tmp
        sourcePath: /app/build/.
    type: Dockerfile
  strategy:
    dockerStrategy:
      from:
        kind: ImageStreamTag
        name: gdx-agreements-tracker-nginx-run:dev
    type: Docker
  successfulBuildsHistoryLimit: 2
  triggers:
  - type: ConfigChange
  - imageChange:
      from:
        kind: ImageStreamTag
        name: gdx-agreements-tracker-nginx-run:dev
    type: ImageChange
  - imageChange:
      from:
        kind: ImageStreamTag
        name: gdx-agreements-tracker-app-build:dev
    type: ImageChange
---
apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  annotations:
    description: Creates the Nginx runtime container.
  labels:
    app: gdx-agreements-tracker
    env: tools
    role: nginx
  name: gdx-agreements-tracker-nginx-run
  namespace: acd38d-tools
spec:
  failedBuildsHistoryLimit: 2
  output:
    to:
      kind: ImageStreamTag
      name: gdx-agreements-tracker-nginx-run:dev
  runPolicy: Serial
  source:
    contextDir: openshift/templates/images/nginx/docker
    git:
      ref: feature/descw-1128-upgrade-images-node-versions
      uri: https://github.com/bcgov/gdx-agreements-tracker.git
    type: Git
  strategy:
    type: Docker
  successfulBuildsHistoryLimit: 2
---
apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  annotations:
    description: The build that generates artifacts (html, javascript, images, etc)
  labels:
    app: gdx-agreements-tracker
    env: tools
    role: api
  name: gdx-agreements-tracker-node-s2i
  namespace: acd38d-tools
spec:
  completionDeadlineSeconds: 1800
  failedBuildsHistoryLimit: 2
  output:
    to:
      kind: ImageStreamTag
      name: gdx-agreements-tracker-node-s2i:dev
  resources:
    limits:
      cpu: 1
      memory: 2Gi
  runPolicy: Parallel
  source:
    contextDir: openshift/templates/images/nodejs
    git:
      ref: feature/descw-1128-upgrade-images-node-versions
      uri: https://github.com/bcgov/gdx-agreements-tracker.git
    type: Git
  strategy:
    type: Docker
  successfulBuildsHistoryLimit: 2
---
apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  annotations:
    description: PostgreSQL runtime container
  labels:
    app: gdx-agreements-tracker
    env: tools
    role: postgres
  name: gdx-agreements-tracker-postgres-run
  namespace: acd38d-tools
spec:
  completionDeadlineSeconds: 1800
  failedBuildsHistoryLimit: 2
  output:
    to:
      kind: ImageStreamTag
      name: gdx-agreements-tracker-postgres-run:dev
  resources:
    limits:
      cpu: "1"
      memory: 6Gi
  runPolicy: Serial
  source:
    contextDir: /openshift/templates/images/postgres
    git:
      ref: feature/descw-1128-upgrade-images-node-versions
      uri: https://github.com/bcgov/gdx-agreements-tracker.git
    type: Git
  strategy:
    dockerStrategy:
      dockerfilePath: Dockerfile
    type: Docker
  successfulBuildsHistoryLimit: 2
---
apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  labels:
    app: gdx-agreements-tracker
    env: tools
  name: nodejs
  namespace: acd38d-tools
spec:
  dockerStrategy:
    forcePull: true
  failedBuildsHistoryLimit: 2
  output:
    to:
      kind: ImageStreamTag
      name: nodejs:latest
  postCommit: {}
  resources: {}
  runPolicy: Serial
  source:
    contextDir: openshift/templates/nodejs/
    git:
      ref: feature/descw-1128-upgrade-images-node-versions
      uri: https://github.com/bcgov/gdx-agreements-tracker.git
    strategy:
      type: Docker
    type: Git
  successfulBuildsHistoryLimit: 2
---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  annotations:
    description: Build Image for the gdx agreements tracker application backend.
  labels:
    app: gdx-agreements-tracker
    env: tools
    role: api
  name: gdx-agreements-tracker-api-build
  namespace: acd38d-tools
---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  annotations:
    description: Final Image for the gdx agreements application backend.
  labels:
    app: gdx-agreements-tracker
    env: tools
    role: api
  name: gdx-agreements-tracker-api-run
  namespace: acd38d-tools
---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  annotations:
    description: This is the image stream for the app build, this will then get combined
      with nginx
  labels:
    app: gdx-agreements-tracker
    env: tools
    role: app
  name: gdx-agreements-tracker-app-build
  namespace: acd38d-tools
---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  annotations:
    description: This is the image stream for the app run
  labels:
    app: gdx-agreements-tracker
    env: tools
    role: app
  name: gdx-agreements-tracker-app-run
  namespace: acd38d-tools
---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  labels:
    app: gdx-agreements-tracker
    env: tools
    role: nginx
  name: gdx-agreements-tracker-nginx-run
  namespace: acd38d-tools
---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  annotations:
    description: The S2i build image for the backend api
  labels:
    app: gdx-agreements-tracker
    env: tools
    role: api
  name: gdx-agreements-tracker-node-s2i
  namespace: acd38d-tools
---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  annotations:
    description: Keeps track of changes to the final runtime deploy image
  labels:
    app: gdx-agreements-tracker
    env: tools
    role: postgres
  name: gdx-agreements-tracker-postgres-run
  namespace: acd38d-tools
spec:
  lookupPolicy:
    local: true
---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  annotations:
    description: Keeps track of NodeJS images that originate from Dockerhub
  labels:
    app: gdx-agreements-tracker
    env: tools
  name: nodejs
  namespace: acd38d-tools
