# this is the volume claim template for the backup container
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: backup-container
    env: v1
    name: pmo-backup
    role: backup-container
  name: pmo-backup-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: netapp-file-backup
---
# For backup verification (pg_verifybackup)
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pmo-backup-verification-pvc
  labels:
    app: backup-container
    env: v1
    name: pmo-backup
    role: backup-container
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: netapp-file-standard
