apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
#namespace: default
resources:
  - backup-db-cron.yaml
  - backup-db-volumes.yaml
commonLabels:
  role: pmo-backups
  app: gdx-agreements-tracker
