name: Test React Application
on:
  pull_request:
    branches:
      - development
    paths:
      - "frontend/**/*"
      - "!openshift/templates/app/docker/Dockerfile*"
      - "!frontend/tsconfig.json"
      - "!frontend/tslint.json"
      - "!frontend/.prettierrc.js"
      - "!frontend/docs"
      - "!frontend/README.md"
      - "!openshift/templates/app/docker/.dockerignore"

  workflow_dispatch:
defaults:
  run:
    working-directory: frontend/
jobs:
  app_lint_and_test_check:
    if: github.repository_owner == 'bcgov'
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: lts/gallium

      - name: Caching node modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Print Node version
        run: node -v

      - name: Install packages
        run: npm install

      - name: Run ESLint
        run: npm run lint

      - name: Run Tests
        run: npm run test
