name: Bump backend version on merge
on:
  pull_request:
      branches:
          - development
      paths:
          - 'backend/**'
jobs:
  bump-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18.14

      - name: Checkout PR
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh pr checkout ${{ github.event.pull_request.number }}
        
      - name: Bump Version
        working-directory: ./backend
        run: npm version minor
      
      - name: Push Changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
            git config user.email "username@users.noreply.github.com"
            git config user.name "$GITHUB_ACTOR"
            git add .
            git commit -m "Bump api version"
            git push
