name: Bump Version

on:
  push:
    branches:
      - development
    paths:
    - "frontend/public/*"
    - "frontend/src/*"

jobs:
  version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN_ACTION }}
      - name: Bump package version